### ISSUE TITLE
tp command

### ISSUE THREAD

**Issue by cethien** [DrexHD/VanillaPermissions#10]
Could be just me being stupid (i'm kinda new to luckyperms stuff) but the `/tp `commands won't work correctly.
I can type `/tp`, can't type any args.

![image](https://github.com/DrexHD/VanillaPermissions/assets/60463918/fc5c099a-7c5f-487b-9cb9-7a6f74b0effd)
![image](https://github.com/DrexHD/VanillaPermissions/assets/60463918/258eb515-9be6-461a-b75f-d11df77480f0)
![image](https://github.com/DrexHD/VanillaPermissions/assets/60463918/32583e02-3b04-41c6-91e7-7f1d608f1173)

**Comment by cethien** [comment]
fixed: also added rule for `minecraft.commands.teleport`

**Comment by DrexHD** [comment]
Looks like you already got it working. The reason `minecraft.commands.tp` (and it's childs) is not enough, is because `/tp` is an alias / redirect to `/teleport`, which "holds" the command / argument logic.
