### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by vocaloidkiss** [DrexHD/VanillaPermissions#12]
![图片](https://github.com/DrexHD/VanillaPermissions/assets/115659586/4539a9dd-29b7-4027-a48f-60bd0f2e76fb)
crash in 1.20.1

**Comment by vocaloidkiss** [comment]
Vanilla Permissions 0.2.2 for 1.20.2
wrong support verson on mordrinth

**Comment by DrexHD** [comment]
I have removed 1.20 and 1.20.1 as supported versions of the 1.20.2 release.
