### ISSUE TITLE
 Incompatibility with Flan

### ISSUE THREAD

**Issue by TheDeathlyCow** [DrexHD/VanillaPermissions#13]
When using [Flan](https://modrinth.com/mod/flan) with Vanilla Permissions, the Flan permission nodes seem to break and are always treated as 'true', even when they are not. I'm not sure which end this issue comes from, so I've also created a report here. 

I am using the following mods: 
- `fabric-api-0.91.2+1.20.2`
- `flan-1.20.2-1.8.11-fabric`
- `LuckPerms-Fabric-5.4.109`
- `vanilla-permissions-0.2.2+1.20.2`

How to reproduce:
1. Install the above mods as listed onto a Fabric 1.20.2 server
2. In the server console, run `/permission user ${your_user_name} permission set luckperms.* true`
3. In game, run `/permission user ${your_user_name} permission set flan.* false`
4. Ensure you are not an operator 
5. Attempt to run a denied Flan command, such as `/flan addClaim ~ ~ ~ ~10 ~ ~10`. This command should fail due to lack of permission, but it will succeed instead. 

Log: https://mclo.gs/vokaI0o
Flan issue: https://github.com/Flemmli97/Flan/issues/269

**Comment by DrexHD** [comment]
I was able to recreate this. But without Vanilla Permissions...
Closing this as invalid, if you think this is a mistake reopen this issue.
