### ISSUE TITLE
Why aren't arguments displayed when trying to teleport?

### ISSUE THREAD

**Issue by alinka62679** [DrexHD/VanillaPermissions#19]
![image](https://github.com/user-attachments/assets/a25d0dd0-a85a-481f-b913-8e04a92a3e44)
![image](https://github.com/user-attachments/assets/f60e69b3-f8b1-4711-8640-a71c7da0a75a)

**Comment by alinka62679** [comment]
It doesn't work that way either
![image](https://github.com/user-attachments/assets/9db9f3b4-2e1d-49fe-b611-b26150d6cbc0)

**Comment by alinka62679** [comment]
mod list
![image](https://github.com/user-attachments/assets/bf94b932-1366-4564-a61d-81bca9d336ca)

**Comment by DrexHD** [comment]
Read https://github.com/DrexHD/VanillaPermissions/issues/22#issuecomment-2402176373 for an in depth explanation of the teleport command permissions.
