### ISSUE TITLE
More granular teleport permissions

### ISSUE THREAD

**Issue by kilrathi** [DrexHD/VanillaPermissions#21]
minecraft.command.tp gives access to coordinate along with players.

Would it be possible to have 2 different permissions?

minecraft.command.tp.player     <--   Allows teleporting to players
minecraft.command.tp.coord     <--   Allows teleporting to coordinates

This way my regular players can use map coords for teleporting which is required by some worldmap mods and I dont give them access to teleport to players unless i want that as well.

**Comment by DrexHD** [comment]
That is already how it works. 
![image](https://github.com/user-attachments/assets/8d45da2b-3776-497f-9c2f-0326d39ec4ac). `/tp` just redirects to `/teleport`. Make sure your permission editor doesn't automatically give all sub-permission!

**Comment by kilrathi** [comment]
Strange, mine doesn't have the extra options.  I may have other issues.  Thank you for the quick response.
