### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by MarijnIsN00B** [DrexHD/VanillaPermissions#9]
I'm trying to use this mod on my server but I'm getting a crash at startup, here are the logs

https://mclo.gs/N83l4YU

Game version is 1.20.1
Fabric version is 0.14.21
Using the latest version of this mod
Server is running with java 17, not sure which distro, but I assume OpenJDK

**Comment by DrexHD** [comment]
I can't reproduce this issue, if this is still an issue, reopen this issue and attach the smallest subset of mods that this occurs with.
